### PR TITLE
Fix CI Failures

### PR DESCRIPTION
**Pull request by Javagedes**
Fix flake8 E275 failures which requires a space after a keyword (in particular, the **assert**, **if**, **elif**, and **else** keywords)
Fix integration test failures due to recent changes in both Project Mu and EDK2

### CODE REVIEW

**Comment by makubacki** [comment]
Since this is just a style change (or should be), can you also get rid of parentheses around conditional expressions after keywords like "if"?

That's a C style that's non-Pythonic and creates a style debt that doesn't align with new code.

**Comment by Javagedes** [comment]
> Since this is just a style change (or should be), can you also get rid of parentheses around conditional expressions after keywords like "if"?
> 
> That's a C style that's non-Pythonic and creates a style debt that doesn't align with new code.

@makubacki This is a style change, but this PR was made because it is a new flake8 rule that we are failing which is causing us to fail CI. While I can remove the parentheses manually, it is not a Flake8 rule, so with the current infrastructure, it cannot be maintained / enforced for future PRs. 

One option I see is to require compliance with both flake8 and pylint. They have a lot of overlap, but also some differences (such as pylint having the parenthesis requirement you're looking for [C0325](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/superfluous-parens.html)).  If you think it is useful to go down this route, we could also throw in [bandit](https://pypi.org/project/bandit/) on the security side too.

Thoughts @makubacki @spbrogan ?

**Comment by makubacki** [comment]
> 

I suggest we get this in for now to resolve the immediate problem and then look at ways to converge linting like you suggested.

**Comment by makubacki** [comment]
This PR has a few unrelated changes. The commits are currently prepared for a squash operation.

Can you please break them out to individual commits and the Rebase & FF the series?

**Comment by makubacki** [comment]
> This PR has a few unrelated changes. The commits are currently prepared for a squash operation.
> 
> Can you please break them out to individual commits and the Rebase & FF the series?

Mostly looks like (1) space change across all files (2) using.md broken link fix (3) some .robot file changes.

**Review by makubacki — APPROVED** [review]
Please help address the few minor comments I left before completing.

**Comment by Javagedes** [comment]
> > This PR has a few unrelated changes. The commits are currently prepared for a squash operation.
> > Can you please break them out to individual commits and the Rebase & FF the series?
> 
> Mostly looks like (1) space change across all files (2) using.md broken link fix (3) some .robot file changes.

I have rebased the commits to represent the three major changes and will rebase & FF when merging. Thanks!

**Review by cfernald — APPROVED** [review]

**Pull request merged**
