### PR TITLE
[Feature]: Automatic Documentation Generation [REBASE&FF]

### PR DESCRIPTION
**Pull request by Javagedes**
Three separate commits to:

1. Set up automatic documentation generation
2. Add a documentation Issue template
3. Fix incorrect style for generating tips, hints, warnings, alerts

**NOTE:** This does not contain the logic to push the static html to readthedocs to be hosted. That PR will happen once I get both edk2toolext and edk2toollib finished so I can add the final pipeline check without blocking edk2toollib.

**ASK:** I definitely ask you clone this branch and run mkdocs serve to take a look at the documentation. Since the plan is to upload to readthedocs, I'm using their theme. I've added a few examples below.

___________________________________

## Example 1
Screenshot 2022-11-28 101631

___________________________________

## Example 2
Screenshot 2022-11-28 101748

### CODE REVIEW

**Comment by makubacki** [comment]
I think `mkdocs-awesome-pages-plugin` is missing in `docs/user/requriements.txt`. I had to manually pip install it to get around this error running mkdocs serve:

```
ERROR    -  Config value: 'plugins'. Error: The "awesome-pages" plugin is not installed
Aborted with 1 Configuration Errors!
```

**Review by makubacki — APPROVED** [review]
Looks good. Generated the docs locally and everything worked fine.

I don't think these show up as unresolved conversations but just comments, so I wanted to call them out here before the PR completes:

- https://github.com/tianocore/edk2-pytool-extensions/pull/348#issuecomment-1329990518
- https://github.com/tianocore/edk2-pytool-extensions/pull/348#issuecomment-1329991193

**Comment by Javagedes** [comment]
> I don't think these show up as unresolved conversations but just comments, so I wanted to call them out here before the PR completes:

Good catches. Will update these after work and get this merged. Thanks!

**Comment by Javagedes** [comment]
@makubacki The documentation section of the base readme has been updated to include steps on how to prepare and use mkdocs. I've also added mkdocs-awesome-pages-plugin to the requirements.txt file.

**Pull request merged**
