### PR TITLE
Add initial support for Azure CLI universal packages as ext_dep type

### PR DESCRIPTION
**Pull request by spbrogan**
See https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops for details on universal packages

### CODE REVIEW

**Comment by spbrogan** [comment]
Unit Tests seem to fail on the server.  Looks like authentication related.  Az cli is not a very good scriptable interface so I am not sure this is going to work.

**Review by corthon — APPROVED** [review]

**Comment by spbrogan** [comment]
@corthon  - there is no cache.  Should we create and manage our own file cache?

**Comment by corthon** [comment]
Yeah, not sure what to do about the auth. Maybe some who have used them in existing pipelines have some ideas? I think this is one of the downsides about it not supporting public feeds (as far as I can tell).

**Comment by spbrogan** [comment]
> Yeah, not sure what to do about the auth. Maybe some who have used them in existing pipelines have some ideas? I think this is one of the downsides about it not supporting public feeds (as far as I can tell).

working on a PAT based solution.  will see if it works

**Comment by spbrogan** [comment]
The PAT solution works but it has lots of limitations because to depends on secret variables in the pipeline which are not allowed for PRs from forks.  I think it will work for actual product development which use devops / private repos and a development process  that leverages "user" branches for PRs in the repo rather than forks.

**Pull request merged**
