### PR TITLE
Pass same build variables to DSC parser as to FDF parser.

### LINKED ISSUE #140: DSC parser should be passed input values from previous parsing steps.
DSC Parser Should be instantiated with values from prior in the parsing project (in particular, from target.txt). Currently it cannot resolve e.g. $(TOOL_CHAIN_TAG). 

**To Reproduce**

Introduce a conditional into the build like the following
!if ("GCC49" in $(TOOL_CHAIN_TAG)) OR ("GCC5" in $(TOOL_CHAIN_TAG))
asdfsadf
!endif

**Expected behavior**
Conditional is properly evaluated. But instead, stack trace.

### PR DESCRIPTION
**Pull request by joschock**
Fixes #140

### CODE REVIEW

**Comment by matthewfcarlson** [comment]
I think this is consistent with #121

**Comment by matthewfcarlson** [comment]
@joschock how have you tested this?

**Comment by joschock** [comment]
Yep - fixes my issue with the problematic DSC conditional. Also rebuilt several projects with this tool, observed no issues.

**Comment by matthewfcarlson** [comment]
I think there's some more work that needs to be done here. But it's approved and you can merge when you're ready

**Comment by joschock** [comment]
Agree; but I think most of that work is deciding/designing how the parser works and what it is allowed to see. I think that should be done as a larger separate effort.

**Comment by joschock** [comment]
I don't have rights to complete the PR.

**Comment by matthewfcarlson** [comment]
Sorry, when I said there was more working to be done I meant more design needed to be done. Our whole approach to passing information from the DSC to the fdf needs to be thought through a little closer

**Pull request merged**
