### PR TITLE
capsule: Update CapsuleHelper to process integrity file

### PR DESCRIPTION
**Pull request by corthon**
Update CapsuleHeader to check for the 'fw_integrity_file' capsule option and,
if present, set the field in the InfGenerator so that the INF file has the
definitions for the integrity file.

### CODE REVIEW

**Comment by spbrogan** [comment]
This is going to put a dependency on pytool library version, right?

**Comment by corthon** [comment]
> This is going to put a dependency on pytool library version, right?

Yes. It will. I should hold this and update the requirements once Library lands.

**Comment by corthon** [comment]
This SHOULD be good to go now.

**Review by spbrogan — APPROVED** [review]
Approve but seems like adding a new option should have some documentation update somewhere even if it is just a function header.

**Comment by corthon** [comment]
Documentation started. Can fill in more if the tools are EVER consumed.

**Pull request merged**
