### PR TITLE
Fix the Repo Resolver

### PR DESCRIPTION
**Pull request by matthewfcarlson**

### CODE REVIEW

**Comment by matthewfcarlson** [comment]
@spbrogan this is ready to go

**Comment by spbrogan** [comment]
Did you run the tests in https://github.com/tianocore/edk2-pytool-extensions/tree/master/integration_test

**Comment by matthewfcarlson** [comment]
Nope- forgot about that. I'll do it tomorrow :)

**Comment by matthewfcarlson** [comment]
@spbrogan I'll be completing this once this passes CI

**Pull request merged**
