### PR TITLE
Update nuget version to 5.3

### PR DESCRIPTION
**Pull request by matthewfcarlson**
Update nuget version to 5.3 from 5.1, which might help with some linux credential provider issues

### CODE REVIEW

**Comment by spbrogan** [comment]
Have you tested on windows?  does this work?  do auth feeds work?  are we confident there are no regressions?

**Comment by matthewfcarlson** [comment]
So thanks to the unit tests we know that most of the nuget functionality works but I will test authenticated feeds in my build tree today

**Comment by spbrogan** [comment]
@matthewfcarlson  waiting on your authenticated feed test

**Comment by matthewfcarlson** [comment]
I tested it on windows on authenticated feeds. I didn't do authenticated feeds on linux, but it looked like it worked well getting a regular feed for linux.

**Pull request merged**
