### PR TITLE
Add a builder's base class so that the user

### PR DESCRIPTION
**Pull request by BobCF**
can create customized builder and make it be consumed by
edk2PlatformBuild. That is to be consumed by stuart_build.exe

Signed-off-by: Bob Feng <bob.c.feng@intel.com>

### CODE REVIEW

**Review by spbrogan — CHANGES_REQUESTED** [review]
I don't think this change makes sense.  Basically because your AbsBuilder is completely abstract you are using stuart_build/edk2_platform_build  just to run a python module that has "go".  At that point what value is using stuart_build?

I think I would suggest you create your own invocable of the type want.  I don't see value in this unless you get code reuse or simplification/scalability.  If with each platform or new generation you are implementing a complete AbsBuilder then you haven't achieved those goals.

**Comment by BobCF** [comment]
> I don't think this change makes sense. Basically because your AbsBuilder is completely abstract you are using stuart_build/edk2_platform_build just to run a python module that has "go". At that point what value is using stuart_build?
> 

No, not just run 'go'.  I want to maximize the reuse of the edk2_platform_build functions. 
The purpose of AbsBuilder is to unbind the edk2_platform_build and UefiBuilder, so that edk2_platform_build can run other command, not only just edk2 build.py. This is the fundamental problem I need to resolve if I use Pytools.


> I think I would suggest you create your own invocable of the type want. I don't see value in this unless you get code reuse or simplification/scalability. If with each platform or new generation you are implementing a complete AbsBuilder then you haven't achieved those goals.

The AbsBuilder is the base class, I won't implement AbsBuilder, I will implement my builder class derive from the AbsBuilder.
I have thought about creating my own invocable and corresponding builder, that will introduce one more new command and there would be much similar code in the new invocable as it in edk2_platform_build.

**Comment by BobCF** [comment]
This PR https://github.com/tianocore/edk2-pytool-extensions/pull/242 is about creating new invocable and builder.

**Comment by Javagedes** [comment]
Closed due to inactivity, feel free to re-open!

**Pull request closed without merging**
